site_name: GridMaster
theme:
  name: material
  features:
    - toc.integrate  # 确保侧边 TOC 出现
    - navigation.expand  # 自动展开导航栏
    - content.code.copy  # 代码块显示复制按钮
    - content.code.annotate  # 代码行注释
    - content.tabs.link  # 标签页之间的上下文链接
    - content.tooltips  # 鼠标悬停提示

nav:
  - Home: index.md
  - Quickstart: usage.md
  - GridMaster Tools:
      - Essential Tools: api/core_api.md
      - Advanced Usage: api/advanced_api.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight  # 启用代码块高亮
  - pymdownx.superfences  # 支持多语言代码块（比如 python）


extra_javascript:
  - js/target-blank.js

extra_css:
  - css/custom.css

site_url: https://gridmaster.readthedocs.io/en/main/
